### ISSUE TITLE
Issue with staticnat and CloudStack 4.5: NameError: global name 'AnsibleCloudStackPortforwarding' is not defined

### ISSUE THREAD

**Issue by milamberspace** [resmo/ansible-cloudstack#28]
TASK: [cs_staticnat] *********************************************************\* 
failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/milamber/.ansible/tmp/ansible-tmp-1440009370.83-101564793180131/cs_staticnat", line 2280, in <module>
    main()
  File "/home/milamber/.ansible/tmp/ansible-tmp-1440009370.83-101564793180131/cs_staticnat", line 657, in main
    acs_static_nat = AnsibleCloudStackStaticNat(module)
  File "/home/milamber/.ansible/tmp/ansible-tmp-1440009370.83-101564793180131/cs_staticnat", line 525, in **init**
    super(AnsibleCloudStackPortforwarding, self).**init**(module)
NameError: global name 'AnsibleCloudStackPortforwarding' is not defined

**Comment by milamberspace** [comment]
Small bug.
See PR https://github.com/resmo/ansible-cloudstack/pull/29

**Comment by resmo** [comment]
thx. my fault...
